-- AI enrichment pipeline (multi-agent LangGraph) persistence.
-- Owned by the scopefoundry-ai Python service, but created here so all schema
-- for the scopefoundry database lives in one migration runner.
--
-- run id is a UUID hex string generated by the Python service (passed in, so the
-- database does not need the pgcrypto/uuid-ossp extension). The LangGraph
-- AsyncPostgresSaver creates its own checkpoint tables via .setup() at startup.

CREATE TABLE IF NOT EXISTS ai_enrichment_runs (
  id          TEXT PRIMARY KEY,
  service_id  BIGINT,                       -- pricebook id (null for an unsaved service)
  status      TEXT NOT NULL DEFAULT 'pending',
  model       TEXT,
  iterations  INTEGER NOT NULL DEFAULT 0,   -- number of Architect passes performed
  qa_overall  NUMERIC,                      -- computed weighted QA score (0-100)
  qa_scores   JSONB,                        -- per-dimension scores + issues
  approved    BOOLEAN,                      -- QA approval (overall>=90 AND min sub>=85)
  input       JSONB,                        -- original service context
  output      JSONB,                        -- final field set
  error       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ai_agent_outputs (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id      TEXT NOT NULL REFERENCES ai_enrichment_runs(id) ON DELETE CASCADE,
  agent       TEXT NOT NULL,                -- 'architect' | 'qa' | 'recommendation' | ...
  iteration   INTEGER NOT NULL DEFAULT 0,
  output      JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_outputs_run ON ai_agent_outputs (run_id);
CREATE INDEX IF NOT EXISTS idx_ai_enrichment_runs_status ON ai_enrichment_runs (status);
